name: dart_bloc_dependency_manager
description: A sample app to demonstrate how to manage bloc dependencies using observer pattern.

version: 1.0.0

environment:
  sdk: ^3.0.2

dependencies:
  bloc: ^8.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
